<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\User as EUser;

/**
 * SocialGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialGroupRepository extends EntityRepository
{
  public function getSocialGroupsByUserId($id) {
    return $this->getEntityManager()
      ->createQuery(
        'SELECT p, g FROM AppBundle:User p
        JOIN p.sgroups g WHERE p.id = ?1'
      )->setParameter(1, $id)->getResult();
  }
}
