app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

better_gists:
    resource: "@BetterGistsBundle/Controller/GistController.php"
    type:     annotation

better_gists_rest:
    resource: "@BetterGistsBundle/Controller/GistRestController.php"
    type:     annotation
    prefix:   /api/v1

better_gists_tags:
    resource: "@BetterGistsBundle/Controller/TagsController.php"
    type:     annotation

upload_product:
    resource: "@UploadBundle/Controller/ProductController.php"
    type:     annotation

upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /upload

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"