app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

gists:
    resource: "@BetterGistsBundle/Controller/GistController.php"
    type:     annotation

gist_public:
    resource: "@BetterGistsBundle/Controller/GistPublicController.php"
    type:     annotation

gists_rest_login:
    resource: "@BetterGistsBundle/Controller/RestLoginController.php"
    type:     annotation
    prefix:   /api

gists_rest:
    resource: "@RestGistBundle/Controller/RestGistController.php"
    type:     annotation
    prefix:   /api/v1

gists_tags:
    resource: "@BetterGistsBundle/Controller/TagsController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest_gist:
    resource: "@RestGistBundle/Controller"
    type:     annotation

