app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

better_gists:
    resource: "@BetterGistsBundle/Controller/GistController.php"
    type:     annotation

better_gists_rest_login:
    resource: "@BetterGistsBundle/Controller/RestLoginController.php"
    type:     annotation
    prefix:   /api

better_gists_tags:
    resource: "@BetterGistsBundle/Controller/TagsController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest_gist:
    resource: "@RestGistBundle/Controller"
    type:     annotation

better_gists_rest:
    resource: "@RestGistBundle/Controller/RestGistController.php"
    type:     annotation
    prefix:   /api/v1
