better_gists:
    resource: "@BetterGistsBundle/Controller/GistController.php"
    type:     annotation
    prefix:   /

app_social_group:
    resource: "@AppBundle/Controller/SocialGroupController.php"
    type:     annotation

rocket_ajax:
    resource: "@RocketAjaxBundle/Controller/"
    type:     annotation
    prefix:   /ajax

rocket_user:
    resource: "@RocketUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

upload_product:
    resource: "@UploadBundle/Controller/ProductController.php"
    type:     annotation

upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /upload

rocket_clients_organizations:
    resource: "@RocketClientsOrganizationsBundle/Resources/config/routing.yml"
    prefix:   /

rocket_clients_contacts:
    resource: "@RocketClientsContactsBundle/Resources/config/routing.yml"
    prefix:   /

rocket_expenses:
    resource: "@RocketExpensesBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"