# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    app.tokens.action_listener:
        class: RestGistBundle\EventListener\TokenListener
        arguments: ['%token_phrase%']
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    jwt.requestparser:
        class:  BetterGistsBundle\DependencyInjection\JwtRequestParser
        arguments: ['%token_phrase%']
    app.gist_voter:
        class: BetterGistsBundle\Security\GistVoter
        tags:
          - { name: security.voter }
        public: false
    app.jwt_issuer:
        class: BetterGistsBundle\DependencyInjection\jwtIssuer
        arguments: ['username']
        calls:
            - [setContainer, ["@service_container"]]
