<?php

namespace BetterGistsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GistRepository extends EntityRepository
{
}
