<?php

namespace BetterGistsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GistRepository extends EntityRepository
{
  public function countAllGists()
  {
    $dql = 'SELECT COUNT (g) AS theCount
            FROM BetterGistsBundle:Gist g';
    $em = $this->getEntityManager();
    $result = $em->createQuery($dql)->getResult();
    $number_of_gists = intval($result[0]['theCount']);
    return $number_of_gists;
  }
  public function getGistsOrderedById()
  {
    $dql = 'SELECT g.id, g.title
            FROM BetterGistsBundle:Gist g
            JOIN g.tags t 
            GROUP BY g.id
            ORDER BY g.id';
    $em = $this->getEntityManager();
    return $em->createQuery($dql)->getResult();
  }
  public function getGistsOrderedByName($firstValue = NULL, $numberOfValues = NULL)
  {
    $dql = 'SELECT g
            FROM BetterGistsBundle:Gist g
            GROUP BY g.id
            ORDER BY g.title';
    $em = $this->getEntityManager();
    if(!is_null($firstValue) && !is_null($numberOfValues)) {
      $results = $em->createQuery($dql)
        ->setMaxResults($numberOfValues)
        ->setFirstResult($firstValue)
        ->getResult();
      return $results;
    } else {
      return $em->createQuery($dql)->getResult();
    }
  }
  public function getGistsOrderedByUpdated($firstValue = NULL, $numberOfValues = NULL)
  {
    $dql = 'SELECT g
            FROM BetterGistsBundle:Gist g
            GROUP BY g.id
            ORDER BY g.updated DESC';
    $em = $this->getEntityManager();
    if(!is_null($firstValue) && !is_null($numberOfValues)) {
      $results = $em->createQuery($dql)
        ->setMaxResults($numberOfValues)
        ->setFirstResult($firstValue)
        ->getResult();
      return $results;
    } else {
      return $em->createQuery($dql)->getResult();
    }
  }
}
